version: '3'

services:
  go-rag:
    image: iwangle/go-rag:v0.0.1
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=go-rag
    volumes:
      # 如果需要持久化配置或数据，可以添加相应的卷挂载，目前是在构建镜像时就copy过去的
      - ./server/manifest:/app/manifest
    depends_on:
      - elasticsearch
      - mysql

  elasticsearch:
    image: elasticsearch:8.11.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - ./data/es_data:/usr/share/elasticsearch/data
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=go-rag
      - MYSQL_ROOT_HOST=%  # 允许root从任意主机连接
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql_data:/var/lib/mysql
    restart: unless-stopped
