server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

database:
  default:
    host: "mysql" # 地址
    port: "3306" # 端口
    user: "root" # 账号
    pass: "123456" # 密码
    name: "go-rag" # 数据库名称
    type: "mysql" # 数据库类型

es:
  address: "http://elasticsearch:9200"
  indexName: "rag-test"
#  username: "elastic"
#  password: "123456"

embedding:
  model: "text-embedding-3-large"
  apiKey: "sk-***"
  baseURL: "https://api.openai.com/v1"

rerank:
  model: "BAAI/bge-reranker-v2-m3"
  apiKey: "sk-***"
  baseURL: "https://api.siliconflow.cn/v1"

qa:
  model: "Qwen/Qwen3-32B"
  apiKey: "sk-***"
  baseURL: "https://api.siliconflow.cn/v1"

chat:
  apiKey: "sk-***"
  baseURL: "https://api.openai.com/v1"
  model: "gpt-4o"
