server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

database:
  default:
    host: "mysql" # 地址
    port: "3306" # 端口
    user: "root" # 账号
    pass: "123456" # 密码
    name: "go-rag" # 数据库名称
    type: "mysql" # 数据库类型

es:
  address: "http://elasticsearch:9200"
  indexName: "rag-test"
#  username: "elastic"
#  password: "123456"

embedding:
  apiKey: "sk-****"
  baseURL: "https://api.siliconflow.cn/v1"
  model: "BAAI/bge-m3"

rerank:
  apiKey: "sk-****"
  baseURL: "https://api.siliconflow.cn/v1"
  model: "BAAI/bge-reranker-v2-m3"

rewrite:
  apiKey: "sk-****"
  baseURL: "https://api.siliconflow.cn/v1"
  model: "Qwen/Qwen3-14B" # 测试下来14b速度最快

qa:
  apiKey: "sk-****"
  baseURL: "https://api.siliconflow.cn/v1"
  model: "Qwen/Qwen3-14B" # 测试下来14b速度最快

chat:
  apiKey: "sk-****"
  baseURL: "https://api.siliconflow.cn/v1"
  model: "Pro/deepseek-ai/DeepSeek-V3"
